---
title: "Influence of alcohol and tobacco usage on esophageal cancer"
subtitle: ""
author: Krzysztof Modrzyński
format: 
  html:
    toc: true
    code-tools: true
    code-line-numbers: true  
    number-sections: true
    mainfont: Georgia, serif
    page-layout: article
  pdf:  
    geometry:
    - left=1cm,top=1cm,bottom=1cm,right=7cm
    number-sections: true
    code-annotations: none
editor: source
---

# Introduction

### Loading the dataset

```{r}
#| > loading dataset
library(medicaldata)
espoh <- medicaldata::esoph_ca
#data(package = "medicaldata")
espoh
```

```{r}
#write.csv(espoh, "C:\\Users\\kmodr\\OneDrive\\Pulpit\\espoh.csv", row.names=FALSE)
```

```{r}
new <- read.csv("espoh/changed_espoh.csv", sep = ",")
new
```

```{r}
library(car)
fit <- lm(ncases/(ncases + ncontrols) ~ alc_low + tob_low + age_low, data = new)
#summary(fit)
avPlots(fit, col = "red")
```

```{r}
#https://www.populationpyramid.net/france/1960/
population <- read.csv("France-1960.csv", sep = ",")
population$total = population$M + population$F
population
```


```{r}
population = population[-(1:5),]
population$age_low = as.numeric(substring(population$Age,1, 2))
population$age_high = as.numeric(substring(population$Age,4, 5))
population = population[, -(1:3)]
population["21", "age_low"] <- 100
population["21", "age_high"] <- 120
population
```


```{r}
#write.csv(population, "population.csv", row.names=FALSE)
pop_new = read.csv("changed_pop.csv", sep = ",")
s = seq(1, 120, 1)
hist(q)
#points(pop_new$age_low + round((pop_new$age_high - pop_new$age_low)/2), pop_new$total/ sum(pop_new$total), col = 'red')
barplot(pop_new$total/sum(pop_new$total))

```




```{r}
# Convert entire dataframe to numeric
df <- data.frame(apply(new, 2, as.numeric))

column_names <- c("Age", "Tobac", "Alco", "Has_cancer")
new_df <- data.frame(matrix(ncol = length(column_names), nrow = 0))
colnames(new_df) <- column_names

for (i in 1:dim(df)[1]) {
  for (j in 1:df[i, "ncases"]) {
    age_sample <- ifelse(df[i, "age_high"] > 0, runif(1, df[i, "age_low"], df[i, "age_high"]), rexp(1, rate = 0.7) + df[i, "age_low"])
    tob_sample <- ifelse(df[i, "tob_high"] > 0, runif(1, df[i, "tob_low"], df[i, "tob_high"]), rexp(1, rate = 0.01) + df[i, "tob_low"])
    alc_sample <- ifelse(df[i, "alc_high"] > 0, runif(1, df[i, "alc_low"], df[i, "alc_high"]), rexp(1, rate = 0.01) + df[i, "alc_low"])
    new_row = data.frame(
      Age = age_sample,
      Tobac = tob_sample,
      Alco = alc_sample,
      Has_cancer = 1
    )
    new_df <- rbind(new_df, new_row)
  }
  for (k in 1:df[i, "ncontrols"]) {
    age_sample <- ifelse(df[i, "age_high"] > 0, runif(1, df[i, "age_low"], df[i, "age_high"]), rexp(1, rate = 0.7) + df[i, "age_low"])
    tob_sample <- ifelse(df[i, "tob_high"] > 0, runif(1, df[i, "tob_low"], df[i, "tob_high"]), rexp(1, rate = 0.01) + df[i, "tob_low"])
    alc_sample <- ifelse(df[i, "alc_high"] > 0, runif(1, df[i, "alc_low"], df[i, "alc_high"]), rexp(1, rate = 0.01) + df[i, "alc_low"])
    new_row = data.frame(
      Age = age_sample,
      Tobac = tob_sample,
      Alco = alc_sample,
      Has_cancer = 0
    )
    new_df <- rbind(new_df, new_row)
  }
}

# Display the resulting dataframe
print(new_df)

```







