---
title: "Influence of alcohol and tobacco usage on esophageal cancer"
subtitle: ""
author: Krzysztof Modrzyński
format: 
  html:
    toc: true
    code-tools: true
    code-line-numbers: true  
    number-sections: true
    mainfont: Georgia, serif
    page-layout: article
  pdf:  
    geometry:
    - left=1cm,top=1cm,bottom=1cm,right=7cm
    number-sections: true
    code-annotations: none
editor: source
---

# Introduction

### Loading the dataset

```{r}
#| > loading dataset
library(medicaldata)
espoh <- medicaldata::esoph_ca
#data(package = "medicaldata")
espoh
```

```{r}
#write.csv(espoh, "C:\\Users\\kmodr\\OneDrive\\Pulpit\\espoh.csv", row.names=FALSE)
```

```{r}
new <- read.csv("changed_espoh.csv", sep = ",")
#

df_case = c()
df_N = c()
df_alc = c()
df_tob = c()
df_age = c()
d = length(new[,1])
for (i in 1:d)
{
  df_case = c(df_case, rep(c(new$ncases[i]), new$ncases[i] + new$ncontrols[i]))
  df_N = c(df_N, rep(c(new$ncases[i] + new$ncontrols[i]), new$ncases[i] + new$ncontrols[i]))
  if (new$alc_high[i] != -1)
  {
  df_alc = c(df_alc, runif(new$ncases[i] + new$ncontrols[i], min = new$alc_low[i], max = new$alc_high[i]))
  } else
  {
  df_alc=c(df_alc, new$alc_low[i] + rexp(new$ncases[i]+new$ncontrols[i], 0.01))
  }
  if (new$tob_high[i] != -1)
  {
  df_tob = c(df_tob, runif(new$ncases[i] + new$ncontrols[i], min = new$tob_low[i], max = new$tob_high[i]))
  } else
  {
  df_tob=c(df_tob, new$tob_low[i]+ rexp(new$ncases[i]+new$ncontrols[i], 0.01))
  }
  if (new$age_high[i] != -1)
  {
  df_age = c(df_age, runif(new$ncases[i] + new$ncontrols[i], min = new$age_low[i], max = new$age_high[i]))
  } else
  {
  df_age=c(df_age, new$age_low[i] + rexp(new$ncases[i]+new$ncontrols[i], 0.7) * 5)
  }
  
}
df = as.data.frame(cbind(df_case, df_N, df_age, df_alc, df_tob))
colnames(df) <- c("cases", "N", "age", "alc", "tob")
df_2 <- df
df
```

```{r}
library(car)
fit <- lm(ncases/(ncases + ncontrols) ~ alc_low + tob_low + age_low, data = new)
#summary(fit)
avPlots(fit, col = "red")
```

```{r}
#https://www.populationpyramid.net/france/1960/
population <- read.csv("France-1960.csv", sep = ",")
population$total = population$M + population$F
population
```


```{r}
population = population[-(1:5),]
population$age_low = as.numeric(substring(population$Age,1, 2))
population$age_high = as.numeric(substring(population$Age,4, 5))
population = population[, -(1:3)]
population["21", "age_low"] <- 100
population["21", "age_high"] <- 120
population
```


```{r}
#write.csv(population, "population.csv", row.names=FALSE)
pop_new = read.csv("changed_pop.csv", sep = ",")
pop_new
s = seq(0, 7, 1)
#points(pop_new$age_low + round((pop_new$age_high - pop_new$age_low)/2), pop_new$total/ sum(pop_new$total), col = 'red')

exp1 <- dexp(s, 0.8)
exp2 <- dexp(s, 0.7)
exp3 <- dexp(s, 0.6)
plot(s, exp1, type = 'l')
lines((pop_new$total[10:15]/sum(pop_new$total[10:15])), type = 'h')
lines(s, exp2, col = 'blue')
lines(s, exp3, col = 'red')
```


```{r}
barplot(pop_new$total)
p <- rep(((pop_new$age_high - pop_new$age_low)/2 + pop_new$age_low), c(pop_new$total))

age_mean <- mean(p)
age_sd <- sd(p)
age_mean
age_sd
```

```{r}
library(cmdstanr)
model_bin = list(N=length(df_2$N),
                      alc = df_2$alc,
                      tob = df_2$tob,
                      age = df_2$age,
                      sample_size = df_2$N
                      )
bin_model = cmdstan_model("./project_binomial.stan")
out <- capture.output(
fit_bin <- bin_model$sample(data=model_bin, refresh=0, show_messages=FALSE, iter_sampling = 400)
)
bin_df <- fit_ber$draws(format = "draws_df")
```

```{r}
library(rstan)
library(bayesplot)
library(dplyr)
library(ggplot2)
library(ggdist) # for stat_dotsinterval
library(posterior)
d <- fit_bin$summary(NULL, "mean")
e <- tail(as.data.frame(d), 1175)$mean
ggplot(df) +
geom_point(
aes(x, y),
data=data.frame(x=df_2$cases/df_2$N, y=e)
) + geom_abline()

```




```{r}
s <- seq(1, 1175, 1)
plot(s, e, col = "red")
points(s, df_2$cases/df_2$N)
ggplot(df, aes(x=df_2$cases/df_2$N ,y= e)) +   
  geom_point()+   
  geom_smooth() + geom_abline()
```
```{r}
library(brms)
# Globally specfiy cmdstan backend for brms
options(brms.backend="cmdstanr")
# Tell brms to cache results if possible
options(brms.file_refit="on_change")

model <- brm(
  formula = bf(cases | trials(N) ~ alc + tob + age),
  family = binomial(),
  prior = c(
    prior(normal(0, 10), class = "Intercept"),
    prior(normal(0, 10), class = "b", coef = "alc"),
    prior(normal(0, 10), class = "b", coef = "tob"),
    prior(normal(0, 10), class = "b", coef = "age")
  ),
  data = df,
  chains = 4
)

```

```{r}
summary(model)
pp_check(model) + yaxis_text()

```

```{r}
df <- data.frame(apply(new, 2, as.numeric))

column_names <- c("Age", "Tobac", "Alco", "Has_cancer")
new_df <- data.frame(matrix(ncol = length(column_names), nrow = 0))
colnames(new_df) <- column_names

for (i in 1:dim(df)[1]) {
  for (j in 1:df[i, "ncases"]) {
    age_sample <- ifelse(df[i, "age_high"] > 0, runif(1, df[i, "age_low"], df[i, "age_high"]), rexp(1, rate = 0.7) + df[i, "age_low"])
    tob_sample <- ifelse(df[i, "tob_high"] > 0, runif(1, df[i, "tob_low"], df[i, "tob_high"]), rexp(1, rate = 0.01) + df[i, "tob_low"])
    alc_sample <- ifelse(df[i, "alc_high"] > 0, runif(1, df[i, "alc_low"], df[i, "alc_high"]), rexp(1, rate = 0.01) + df[i, "alc_low"])
    new_row = data.frame(
      Age = age_sample,
      Tobac = tob_sample,
      Alco = alc_sample,
      Has_cancer = 1
    )
    new_df <- rbind(new_df, new_row)
  }
  for (k in 1:df[i, "ncontrols"]) {
    age_sample <- ifelse(df[i, "age_high"] > 0, runif(1, df[i, "age_low"], df[i, "age_high"]), rexp(1, rate = 0.7) + df[i, "age_low"])
    tob_sample <- ifelse(df[i, "tob_high"] > 0, runif(1, df[i, "tob_low"], df[i, "tob_high"]), rexp(1, rate = 0.01) + df[i, "tob_low"])
    alc_sample <- ifelse(df[i, "alc_high"] > 0, runif(1, df[i, "alc_low"], df[i, "alc_high"]), rexp(1, rate = 0.01) + df[i, "alc_low"])
    new_row = data.frame(
      Age = age_sample,
      Tobac = tob_sample,
      Alco = alc_sample,
      Has_cancer = 0
    )
    new_df <- rbind(new_df, new_row)
  }
}

# Display the resulting dataframe
print(new_df)
```

```{r}
model_ber = list(N=length(new_df$Has_cancer),
                      alc = new_df$Alco,
                      tob = new_df$Tobac,
                      age = new_df$Age,
                      cancer = new_df$Has_cancer
                      )
ber_model = cmdstan_model("./bernulli_project.stan")
out <- capture.output(
fit_ber <- ber_model$sample(data=model_ber, refresh=0, show_messages=FALSE, iter_sampling = 400)
)
ber_df <- fit_ber$draws(format = "draws_df")
```
```{r}
dber <- fit_ber$summary(NULL, "mean")
eber <- tail(as.data.frame(dber), 1175)$mean
ggplot(df_2) +
geom_point(
aes(x, y),
data=data.frame(x=df_2$cases/df_2$N, y=eber)
) + geom_abline()
```


```{r}
plot(s, eber, col = "red")
points(s, df_2$cases/df_2$N)
ggplot(df_2, aes(x=df_2$cases/df_2$N ,y= eber)) +   
  geom_point()+   
  geom_smooth() + geom_abline()
```









